export const PARAMETERS_FILTERS = [
  { type: 'diameters', values: [13, 14, 15, 16, 17, 18, 19, 20], title: 'Диаметр' },
  { type: 'widths', values: ['5.0', '5.5', '6.0', '6.5', '7.0', '7.5', '8.0', '8.5'], title: 'Ширина' },
  { type: 'mountHoles', values: [4, 5, 6], title: 'Количество крепежных отверстий' },
  {
    type: 'holeDiameters',
    values: ['98', '100', '105', '108', '110', '112', '114.3', '115', '121', '120', '127', '130', '139.7', '150'],
    title: 'Диаметр расположенных отверстий',
  },
  {
    type: 'offset',
    values: [
      '-20',
      '-5',
      '0',
      '15',
      '16',
      '36',
      '41',
      '47.5',
      '48',
      '48.5',
      '49',
      '3',
      '5',
      '50',
      '48.2',
      '48.3',
      '49.2',
      '30',
      '31',
      '32',
      '33',
      '38',
      '51',
      '52',
      '53',
      '55',
      '59',
      '60',
      '62',
      '63',
      '64',
      '65',
      '66',
      '67',
      '68',
      '69',
      '70',
      '71',
      '72',
      '73',
      '74',
      '75',
      '76',
      '77',
      '78',
      '79',
      '80',
      '81',
      '82',
      '83',
    ],
    title: 'Вылет',
  },
]

export const CAR_FILTERS = [
  {
    type: 'mark',
    values: [
      'Toyota',
      'Ford',
      'Chevrolet',
      'Honda',
      'Nissan',
      'Mercedes-Benz',
      'BMW',
      'Volkswagen',
      'Hyundai',
      'Audi',
      'Lexus',
      'Subaru',
      'Mazda',
      'Kia',
      'Porsche',
      'Jaguar',
      'Land Rover',
      'Fiat',
      'Volvo',
      'Tesla',
      'Mitsubishi',
      'Acura',
      'Infiniti',
      'Cadillac',
      'Bentley',
      'Peugeot',
      'Renault',
      'Alfa Romeo',
      'Dodge',
      'Chrysler',
      'GMC',
      'Jeep',
      'Lincoln',
      'Buick',
      'Ram',
      'Skoda',
      'Mini',
      'Aston Martin',
      'Maserati',
      'Ferrari',
      'Lamborghini',
      'Rolls-Royce',
      'Bugatti',
      'Citroen',
      'Dacia',
      'Suzuki',
      'Saab',
      'Seat',
      'Lancia',
      'Opel',
    ],
    title: 'Марка',
  },
]

export const CAR_MODELS_BY_MARK = [
  {
    mark: 'Toyota',
    models: [
      'Camry',
      'Corolla',
      'RAV4',
      'Highlander',
      'Tacoma',
      'Tundra',
      'Prius',
      'Land Cruiser',
      '4Runner',
      'Avalon',
    ],
  },
  {
    mark: 'Ford',
    models: ['F-150', 'Mustang', 'Explorer', 'Escape', 'Edge', 'Ranger', 'Bronco', 'Expedition', 'Fusion', 'EcoSport'],
  },
  {
    mark: 'Chevrolet',
    models: [
      'Silverado',
      'Equinox',
      'Malibu',
      'Camaro',
      'Tahoe',
      'Traverse',
      'Colorado',
      'Suburban',
      'Blazer',
      'Trailblazer',
    ],
  },
  {
    mark: 'Honda',
    models: ['Civic', 'Accord', 'CR-V', 'Pilot', 'Fit', 'Odyssey', 'HR-V', 'Ridgeline', 'Passport', 'Insight'],
  },
  {
    mark: 'Nissan',
    models: ['Altima', 'Rogue', 'Sentra', 'Maxima', 'Murano', 'Pathfinder', 'Frontier', 'Titan', 'Versa', 'Armada'],
  },
  {
    mark: 'Mercedes-Benz',
    models: ['C-Class', 'E-Class', 'S-Class', 'GLE', 'GLC', 'GLS', 'A-Class', 'CLS', 'SL', 'AMG GT'],
  },
  { mark: 'BMW', models: ['3 Series', '5 Series', 'X5', 'X3', '1 Series', '7 Series', 'X1', 'X6', 'Z4', 'i3'] },
  {
    mark: 'Volkswagen',
    models: ['Golf', 'Passat', 'Tiguan', 'Jetta', 'Arteon', 'Atlas', 'Polo', 'Touareg', 'T-Cross', 'ID.4'],
  },
  {
    mark: 'Hyundai',
    models: ['Elantra', 'Sonata', 'Tucson', 'Santa Fe', 'Kona', 'Palisade', 'Veloster', 'Ioniq', 'Nexo', 'Venue'],
  },
  { mark: 'Audi', models: ['A4', 'A3', 'A6', 'Q5', 'Q7', 'A5', 'Q3', 'A8', 'TT', 'Q8'] },
  { mark: 'Lexus', models: ['RX', 'ES', 'NX', 'LS', 'UX', 'GX', 'IS', 'LC', 'LX', 'RC'] },
  {
    mark: 'Subaru',
    models: ['Outback', 'Forester', 'Crosstrek', 'Impreza', 'Legacy', 'WRX', 'BRZ', 'Ascent', 'Solterra', 'XV'],
  },
  {
    mark: 'Mazda',
    models: ['CX-5', 'Mazda3', 'Mazda6', 'CX-9', 'CX-30', 'MX-5 Miata', 'CX-3', 'Mazda2', 'RX-8', 'CX-50'],
  },
  {
    mark: 'Kia',
    models: ['Sorento', 'Sportage', 'Optima', 'Soul', 'Forte', 'Telluride', 'Rio', 'Stinger', 'Niro', 'Sedona'],
  },
  {
    mark: 'Porsche',
    models: ['911', 'Cayenne', 'Macan', 'Panamera', 'Taycan', 'Boxster', 'Cayman', '918 Spyder', 'Carrera GT', '718'],
  },
  { mark: 'Jaguar', models: ['F-Pace', 'XE', 'XF', 'F-Type', 'E-Pace', 'I-Pace', 'XJ', 'XK', 'S-Type', 'X-Type'] },
  {
    mark: 'Land Rover',
    models: [
      'Range Rover',
      'Discovery',
      'Defender',
      'Range Rover Sport',
      'Range Rover Evoque',
      'Discovery Sport',
      'Range Rover Velar',
      'Freelander',
      'LR4',
      'LR2',
    ],
  },
  { mark: 'Fiat', models: ['500', 'Punto', 'Panda', 'Tipo', '500X', '500L', '124 Spider', 'Doblo', 'Fiorino', 'Qubo'] },
  { mark: 'Volvo', models: ['XC90', 'XC60', 'S60', 'V60', 'XC40', 'S90', 'V90', 'C40', 'S80', 'XC70'] },
  {
    mark: 'Tesla',
    models: [
      'Model S',
      'Model 3',
      'Model X',
      'Model Y',
      'Roadster',
      'Cybertruck',
      'Model S Plaid',
      'Model X Plaid',
      'Roadster 2022',
      'Semi',
    ],
  },
  {
    mark: 'Mitsubishi',
    models: ['Outlander', 'Eclipse Cross', 'Lancer', 'Pajero', 'Mirage', 'ASX', 'Montero', 'L200', 'Space Star', 'RVR'],
  },
  { mark: 'Acura', models: ['MDX', 'RDX', 'TLX', 'ILX', 'NSX', 'RLX', 'TSX', 'ZDX', 'Integra', 'CL'] },
  { mark: 'Infiniti', models: ['Q50', 'QX60', 'QX80', 'Q60', 'QX50', 'QX30', 'Q70', 'FX', 'JX', 'G35'] },
  { mark: 'Cadillac', models: ['Escalade', 'XT5', 'CTS', 'CT6', 'XT4', 'ATS', 'XTS', 'SRX', 'CT5', 'ELR'] },
  {
    mark: 'Bentley',
    models: [
      'Continental GT',
      'Bentayga',
      'Flying Spur',
      'Mulsanne',
      'Arnage',
      'Azure',
      'Brooklands',
      'Continental Flying Spur',
      'Bacalar',
      'Blower',
    ],
  },
  { mark: 'Peugeot', models: ['508', '3008', '208', '5008', '308', '2008', '407', '107', '206', 'RCZ'] },
  {
    mark: 'Renault',
    models: ['Clio', 'Megane', 'Kadjar', 'Captur', 'Twingo', 'Scenic', 'Koleos', 'Zoe', 'Laguna', 'Talisman'],
  },
  {
    mark: 'Alfa Romeo',
    models: ['Giulia', 'Stelvio', '4C', 'Giulietta', '159', 'Brera', 'Spider', 'MiTo', '156', 'GTV'],
  },
  {
    mark: 'Dodge',
    models: ['Charger', 'Challenger', 'Durango', 'Ram', 'Journey', 'Dart', 'Nitro', 'Viper', 'Caliber', 'Avenger'],
  },
  {
    mark: 'Chrysler',
    models: [
      '300',
      'Pacifica',
      'Voyager',
      'PT Cruiser',
      '200',
      'Sebring',
      'Town & Country',
      'Aspen',
      'Crossfire',
      'Concorde',
    ],
  },
  {
    mark: 'GMC',
    models: ['Sierra', 'Yukon', 'Acadia', 'Canyon', 'Terrain', 'Savana', 'Envoy', 'Jimmy', 'Sonoma', 'Suburban'],
  },
  {
    mark: 'Jeep',
    models: [
      'Wrangler',
      'Grand Cherokee',
      'Cherokee',
      'Renegade',
      'Compass',
      'Gladiator',
      'Patriot',
      'Commander',
      'Liberty',
      'Wagoneer',
    ],
  },
  {
    mark: 'Lincoln',
    models: ['Navigator', 'MKC', 'Continental', 'MKZ', 'Nautilus', 'Aviator', 'Town Car', 'MKT', 'MKX', 'Corsair'],
  },
  {
    mark: 'Buick',
    models: [
      'Enclave',
      'Encore',
      'Regal',
      'LaCrosse',
      'Verano',
      'Envision',
      'Lucerne',
      'Century',
      'Park Avenue',
      'Riviera',
    ],
  },
  {
    mark: 'Ram',
    models: ['1500', '2500', '3500', 'ProMaster', 'ProMaster City', '1500 Classic', 'Dakota', 'C/V', '4500', '5500'],
  },
  {
    mark: 'Skoda',
    models: ['Octavia', 'Superb', 'Kodiaq', 'Fabia', 'Karoq', 'Yeti', 'Rapid', 'Scala', 'Felicia', 'Citigo'],
  },
  {
    mark: 'Mini',
    models: [
      'Cooper',
      'Countryman',
      'Clubman',
      'Cooper SE',
      'Paceman',
      'Roadster',
      'Coupe',
      'Convertible',
      'John Cooper Works',
      'Electric',
    ],
  },
  {
    mark: 'Aston Martin',
    models: ['DB11', 'Vantage', 'DBS Superleggera', 'DB9', 'DBX', 'Rapide', 'Vanquish', 'Virage', 'DB7', 'One-77'],
  },
  {
    mark: 'Maserati',
    models: [
      'Ghibli',
      'Quattroporte',
      'Levante',
      'GranTurismo',
      'MC20',
      'GranCabrio',
      'Spyder',
      'Coupe',
      '3200 GT',
      'MC12',
    ],
  },
  {
    mark: 'Ferrari',
    models: [
      '488 GTB',
      '812 Superfast',
      'F8 Tributo',
      'Portofino',
      'California T',
      'LaFerrari',
      '458 Italia',
      'SF90 Stradale',
      'Roma',
      '488 Spider',
    ],
  },
  {
    mark: 'Lamborghini',
    models: [
      'Aventador',
      'Huracan',
      'Gallardo',
      'Murcielago',
      'Diablo',
      'Countach',
      'Urus',
      'Miura',
      'Reventon',
      'Veneno',
    ],
  },
  {
    mark: 'Rolls-Royce',
    models: [
      'Phantom',
      'Ghost',
      'Wraith',
      'Dawn',
      'Cullinan',
      'Silver Shadow',
      'Silver Spirit',
      'Silver Spur',
      'Silver Seraph',
      'Corniche',
    ],
  },
  {
    mark: 'Bugatti',
    models: [
      'Chiron',
      'Veyron',
      'EB110',
      'Divo',
      'Centodieci',
      'Bolide',
      'La Voiture Noire',
      'Veyron Grand Sport',
      'Veyron Super Sport',
      'Chiron Pur Sport',
    ],
  },
  { mark: 'Citroen', models: ['C3', 'C4', 'C5', 'Berlingo', 'DS3', 'DS4', 'DS5', 'C3 Aircross', 'C4 Picasso', 'C1'] },
  {
    mark: 'Dacia',
    models: [
      'Duster',
      'Sandero',
      'Logan',
      'Stepway',
      'Sandero Stepway',
      'Logan MCV',
      'Spring Electric',
      'Lodgy',
      'Dokker',
      'Dokker Van',
    ],
  },
  {
    mark: 'Suzuki',
    models: ['Swift', 'Vitara', 'SX4', 'Jimny', 'Baleno', 'Celerio', 'Ignis', 'Alto', 'Wagon R', 'S-Cross'],
  },
  { mark: 'Saab', models: ['9-3', '9-5', '900', '9000', '9-2X', '9-4X', '9-7X', 'Sonett', '96', '93'] },
  {
    mark: 'Seat',
    models: ['Ibiza', 'Leon', 'Arona', 'Ateca', 'Tarraco', 'Alhambra', 'Mii', 'Exeo', 'Toledo', 'Cordoba'],
  },
  {
    mark: 'Lancia',
    models: ['Ypsilon', 'Delta', 'Thesis', 'Musa', 'Phedra', 'Kappa', 'Lybra', 'Dedra', 'Zeta', 'Prisma'],
  },
  {
    mark: 'Opel',
    models: ['Astra', 'Corsa', 'Insignia', 'Vectra', 'Zafira', 'Meriva', 'Mokka', 'Vivaro', 'Combo', 'Adam'],
  },
]

export const PARAMETERS_TIRES_FILTERS = [
  { type: 'diameters', values: ['5.0', '5.5', '6.0', '6.5', '7.0', '7.5', '8.0', '8.5'], title: 'Ширина' },
  { type: 'widths', values: ['5.0', '5.5', '6.0', '6.5', '7.0', '7.5', '8.0', '8.5'], title: 'Профиль' },
  { type: 'mountHoles', values: [4, 5, 6], title: 'Диаметр' },
  {
    type: 'holeDiameters',
    values: ['Michelin', 'Goodyear ', 'Continental '],
    title: 'Бренд',
  },
]
